"""add review_decisions and review_comments

Revision ID: 2026_04_18_1441
Revises: edaa014c2adf
Create Date: 2026-04-18 14:41:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_04_18_1441'
down_revision: Union[str, Sequence[str], None] = 'edaa014c2adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_decisions',
    sa.Column('document_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comments',
    sa.Column('document_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comments')
    op.drop_table('review_decisions')
    # ### end Alembic commands ###
