"""add chunks and update vector_collections

Revision ID: 2026_04_18_1708
Revises: 2026_04_18_1441_add_review_decisions_and_review_comments
Create Date: 2026-04-18 17:08:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_04_18_1708'
down_revision: Union[str, Sequence[str], None] = '2026_04_18_1441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_job_id'), 'chunks', ['job_id'], unique=False)
    
    # Update vector_collections table schema
    # Drop the old foreign key constraint
    op.drop_constraint('vector_collections_job_id_fkey', 'vector_collections', type_='foreignkey')
    
    # Change job_id to allow NULL (SET NULL)
    op.alter_column('vector_collections', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    
    # Recreate foreign key with ON DELETE SET NULL
    op.create_foreign_key('vector_collections_job_id_fkey', 'vector_collections', 'ingestion_jobs', ['job_id'], ['id'], ondelete='SET NULL')
    
    # Add new columns to vector_collections
    op.add_column('vector_collections', sa.Column('embedding_model', sa.String(length=100), nullable=False, server_default='BAAI/bge-small-en-v1.5'))
    op.add_column('vector_collections', sa.Column('vector_dimensions', sa.Integer(), nullable=False, server_default='384'))
    op.add_column('vector_collections', sa.Column('vector_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vector_collections', sa.Column('document_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vector_collections', sa.Column('status', sa.String(length=20), nullable=False, server_default='creating'))
    op.add_column('vector_collections', sa.Column('error_message', sa.Text(), nullable=True))
    
    # Drop old columns that are no longer needed
    op.drop_column('vector_collections', 'qdrant_collection_name')
    op.drop_column('vector_collections', 'chunk_count')
    op.drop_column('vector_collections', 'embedded_at')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_collections', sa.Column('embedded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vector_collections', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vector_collections', sa.Column('qdrant_collection_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    
    op.drop_column('vector_collections', 'error_message')
    op.drop_column('vector_collections', 'status')
    op.drop_column('vector_collections', 'document_count')
    op.drop_column('vector_collections', 'vector_count')
    op.drop_column('vector_collections', 'vector_dimensions')
    op.drop_column('vector_collections', 'embedding_model')
    
    op.create_foreign_key('vector_collections_job_id_fkey', 'vector_collections', 'ingestion_jobs', ['job_id'], ['id'])
    
    op.alter_column('vector_collections', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    
    op.drop_index(op.f('ix_chunks_job_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
